name: "CV"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/21c937f8cb1.tar.gz
    - run: |
        nix-build
        export TIMESTAMP=$(date +%Y%m%dT%H%M%S)
        gh auth login --with-token <<<${{ secrets.GITHUB_TOKEN }}
        gh release create $TIMESTAMP result/cv.pdf result/cv_en.pdf
